# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        mvn clean install -DskipTests
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
          name: jar file
          path: target/*.jar

  test:

    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven
      - name: Run JUnit tests
        run: |
          mvn clean test site
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test report
          path: target/site

  notification:
    needs: test
    runs-on: ubuntu-latest
    if: success() # Executa apenas se o trabalho anterior for bem-sucedido
    steps:
      - name: Send notification on success
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 'Build e Testes Concluídos com Sucesso: ${{ github.repository }}'
          to: seu-email@dominio.com
          from: GitHub Actions <github-actions@example.com>
          body: |
            O workflow para o repositório ${{ github.repository }} foi concluído com sucesso.
            Commit: ${{ github.sha }}
            Pode ver os artefactos de build e os relatórios de teste no resumo da execução da Action.